pipelines:
  default:
    tags:
      production-*:
        - step:
            script:
             - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
             - docker build -t udaysh/python:$BITBUCKET_COMMIT .
             - docker push udaysh/python:$BITBUCKET_COMMIT
options:
    docker: true